requireAuth();
setupLogout();

const cart = new Map();
const formatMoney = value => Number(value).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const productImage = image => image || 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=300&q=80';
const message = (text, type = 'success') => { const element = document.querySelector('[data-message]'); element.textContent = text; element.className = `message ${type}`; };

async function loadSalePage() {
    const clientSelect = document.querySelector('[data-client]');
    clientSelect.previousElementSibling.innerHTML = 'Cliente <a class="field-link" href="cliente.html">Cadastrar cliente</a>';
    const productResults = document.querySelector('[data-product-results]');
    const search = document.querySelector('[data-product-search]');
    const renderProducts = products => { productResults.innerHTML = products.length ? products.map(product => `<article class="sale-product"><img src="${productImage(product.imagem)}" alt=""><div><strong>${escapeHtml(product.titulo)}</strong><span>${escapeHtml(product.autor)}</span><small>${formatMoney(product.preco)} · ${product.quantidade} disponíveis</small></div><button class="button secondary" data-add="${product.id}" ${product.quantidade < 1 ? 'disabled' : ''}>Adicionar</button></article>`).join('') : '<p class="empty">Nenhum produto encontrado.</p>'; productResults.querySelectorAll('[data-add]').forEach(button => button.addEventListener('click', async () => { const product = products.find(item => item.id === Number(button.dataset.add)); addToCart(product); })); };
    const searchProducts = async () => { try { renderProducts(await apiRequest(`/livros${search.value.trim() ? `?busca=${encodeURIComponent(search.value.trim())}` : ''}`)); } catch (error) { message(error.message, 'error'); } };
    try { const clients = await apiRequest('/clientes'); clientSelect.innerHTML = '<option value="">Cliente não identificado</option>' + clients.map(client => `<option value="${client.id}">${escapeHtml(client.nome)}</option>`).join(''); await searchProducts(); } catch (error) { message(error.message, 'error'); }
    search.addEventListener('input', searchProducts);
    document.querySelector('[data-discount]').addEventListener('input', renderCart);
    document.querySelector('[data-discount-type]').addEventListener('change', renderCart);
    document.querySelector('[data-payment]').addEventListener('change', updatePaymentFields);
    document.querySelector('[data-sale-form]').addEventListener('submit', submitSale);
    updatePaymentFields(); renderCart();
}

function addToCart(product) { const current = cart.get(product.id); if (current) { if (current.quantidade < current.quantidadeDisponivel) current.quantidade += 1; } else cart.set(product.id, { ...product, quantidade: 1, quantidadeDisponivel: product.quantidade }); renderCart(); }
function renderCart() { const list = document.querySelector('[data-cart]'); const discount = Number(document.querySelector('[data-discount]').value) || 0; const type = document.querySelector('[data-discount-type]').value; const subtotal = [...cart.values()].reduce((sum, item) => sum + item.preco * item.quantidade, 0); const discountValue = type === 'percentual' ? subtotal * discount / 100 : discount; list.innerHTML = cart.size ? [...cart.values()].map(item => `<div class="cart-row"><div><strong>${escapeHtml(item.titulo)}</strong><small>${formatMoney(item.preco)} cada · máximo ${item.quantidadeDisponivel}</small></div><input type="number" min="1" max="${item.quantidadeDisponivel}" value="${item.quantidade}" data-quantity="${item.id}"><strong>${formatMoney(item.preco * item.quantidade)}</strong><button type="button" class="icon-button" data-remove="${item.id}" aria-label="Remover">×</button></div>`).join('') : '<p class="empty">O carrinho está vazio.</p>'; list.querySelectorAll('[data-remove]').forEach(button => button.addEventListener('click', () => { cart.delete(Number(button.dataset.remove)); renderCart(); })); list.querySelectorAll('[data-quantity]').forEach(input => input.addEventListener('change', () => { const item = cart.get(Number(input.dataset.quantity)); const value = Number(input.value); if (item && value > 0 && value <= item.quantidadeDisponivel) item.quantidade = value; renderCart(); })); document.querySelector('[data-subtotal]').textContent = formatMoney(subtotal); document.querySelector('[data-discount-value]').textContent = formatMoney(Math.min(Math.max(discountValue, 0), subtotal)); document.querySelector('[data-total]').textContent = formatMoney(Math.max(subtotal - discountValue, 0)); updatePaymentFields(); }
function updatePaymentFields() { const payment = document.querySelector('[data-payment]').value; const cash = document.querySelector('[data-cash]'); cash.hidden = payment !== 'Dinheiro'; if (payment === 'PIX') document.querySelector('[data-payment-note]').textContent = 'PIX ficará pendente até uma confirmação real de pagamento.'; else if (payment.includes('Cartão')) document.querySelector('[data-payment-note]').textContent = 'Nenhum dado sensível do cartão será armazenado.'; else document.querySelector('[data-payment-note]').textContent = ''; }
async function submitSale(event) { event.preventDefault(); if (!cart.size) { message('Adicione pelo menos um produto ao carrinho.', 'error'); return; } const type = document.querySelector('[data-discount-type]').value; const payload = { clienteId: document.querySelector('[data-client]').value ? Number(document.querySelector('[data-client]').value) : null, desconto: Number(document.querySelector('[data-discount]').value) || 0, tipoDesconto: type, formaPagamento: document.querySelector('[data-payment]').value, valorRecebido: document.querySelector('[data-cash-value]').value ? Number(document.querySelector('[data-cash-value]').value) : null, itens: [...cart.values()].map(item => ({ produtoId: item.id, quantidade: item.quantidade })) }; try { const sale = await apiRequest('/vendas', { method: 'POST', body: JSON.stringify(payload) }); renderReceipt(sale); cart.clear(); renderCart(); document.querySelector('[data-sale-form]').reset(); updatePaymentFields(); } catch (error) { message(error.message, 'error'); } }
function renderReceipt(sale) { const receipt = document.querySelector('[data-receipt]'); receipt.hidden = false; receipt.innerHTML = `<h2>FE.ESTOQUE</h2><p>Venda #${String(sale.id).padStart(6, '0')}</p><p>${new Date(sale.dataVenda).toLocaleString('pt-BR')}</p><hr><p>Total: <strong>${formatMoney(sale.total)}</strong></p><p>Pagamento: ${escapeHtml(sale.formaPagamento)} · ${escapeHtml(sale.status)}</p>${sale.troco ? `<p>Troco: ${formatMoney(sale.troco)}</p>` : ''}<button class="button primary no-print" data-print>Imprimir comprovante</button>`; receipt.querySelector('[data-print]').addEventListener('click', () => window.print()); message('Venda registrada e estoque atualizado.'); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character])); }
loadSalePage();
